main: me.devnatan.pickupore.PickupOre
name: PickupOre
version: 1.0
author: DevNatan
depend: [Vault]
website: https://github.com/DevNatan
description: Copyright (c) 2018 DevNatan. Todos os direitos reservados.